// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-RSaUlF49HjPB-Zo4e8t1KwGrwQ0M8ug',
    appId: '1:150574980893:web:3b0b46117f036f013fcbf4',
    messagingSenderId: '150574980893',
    projectId: 'twitter-6bbcc',
    authDomain: 'twitter-6bbcc.firebaseapp.com',
    storageBucket: 'twitter-6bbcc.firebasestorage.app',
    measurementId: 'G-XG1WWSTL6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvyjkywR5FH2rlGkSfnQ71dYQ_604pyA',
    appId: '1:150574980893:android:935e5296f3d8ad6e3fcbf4',
    messagingSenderId: '150574980893',
    projectId: 'twitter-6bbcc',
    storageBucket: 'twitter-6bbcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHFIHl22KkpqljegctwNMN4gz7V9MytVs',
    appId: '1:150574980893:ios:170f41d229f43c883fcbf4',
    messagingSenderId: '150574980893',
    projectId: 'twitter-6bbcc',
    storageBucket: 'twitter-6bbcc.firebasestorage.app',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHFIHl22KkpqljegctwNMN4gz7V9MytVs',
    appId: '1:150574980893:ios:170f41d229f43c883fcbf4',
    messagingSenderId: '150574980893',
    projectId: 'twitter-6bbcc',
    storageBucket: 'twitter-6bbcc.firebasestorage.app',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-RSaUlF49HjPB-Zo4e8t1KwGrwQ0M8ug',
    appId: '1:150574980893:web:338086d3123c18e13fcbf4',
    messagingSenderId: '150574980893',
    projectId: 'twitter-6bbcc',
    authDomain: 'twitter-6bbcc.firebaseapp.com',
    storageBucket: 'twitter-6bbcc.firebasestorage.app',
    measurementId: 'G-8WP74GBTS6',
  );

}